services:
  diarization-service:
    build:
      context: ./SVC-SPEECH-DIAR
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    deploy: # Pyannote тоже любит GPU
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./diarize_models:/app/models/diarization:ro
      - ./SVC-SPEECH-DIAR/config:/app/config:ro
    environment:
      - CONFIG_PATH=/app/config/config.yml
    env_file:
      - ./SVC-SPEECH-DIAR/.env
    restart: unless-stopped
    networks:
      - astrachat-network

networks:
  astrachat-network:
    driver: bridge