services:
  ocr-service:
    build:
      context: ./SVC-OCR
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    deploy: # Surya любит GPU
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./SVC-OCR/config:/app/config:ro
      - ./surya_models:/app/models/surya
    environment:
      - DATALAB_CACHE_DIR=/app/models/surya
      - HF_HOME=/app/models/surya
      - HF_HUB_CACHE=/app/models/surya
      - TRANSFORMERS_CACHE=/app/models/surya
    env_file:
      - ./SVC-OCR/.env
    restart: unless-stopped
    networks:
      - astrachat-network

networks:
  astrachat-network:
    driver: bridge